"""
clfs_headers_mapping.py

Static, manually-created mapping of sanitized keys to original CLFS headers.
Use this file to reference columns programmatically without generating the mapping at runtime.

Example:
  from clfs_headers_mapping import HEADERS_MAPPING
  orig = HEADERS_MAPPING['full_name']['header']
  idx = HEADERS_MAPPING['full_name']['index']
"""

HEADERS_MAPPING = {
    'ability_to_apply_the_skills_to_your_jobbusiness': {'header': "Ability to apply the skill(s) to your job/business", 'index': 62},
    'ability_to_apply_the_skills_to_your_jobbusiness_2': {'header': "Ability to apply the skill(s) to your job/business", 'index': 64},
    'ability_to_apply_the_skills_to_your_jobbusiness_3': {'header': "Ability to apply the skill(s) to your job/business", 'index': 66},
    'ability_to_apply_the_skills_to_your_jobbusiness_4': {'header': "Ability to apply the skill(s) to your job/business", 'index': 68},
    'ability_to_apply_the_skills_to_your_jobbusiness_5': {'header': "Ability to apply the skill(s) to your job/business", 'index': 70},
    'actively_sought_additional_hours_of_work_in_the_past_four_weeks': {'header': 'Actively sought additional hours of work in the past four weeks?', 'index': 88},
    'age': {'header': 'Age', 'index': 2},
    'any_breaks_in_employment': {'header': 'Any breaks in employment?', 'index': 116},
    'are_you_actively_looking_for_a_new_job': {'header': 'Are you actively looking for a new job?', 'index': 101},
    'are_you_an_ownerpartner_of_an_acraregistered_business_in_this_job': {'header': 'Are you an owner/partner of an ACRA-registered business in this job?', 'index': 40},
    'are_you_available_to_start_work_on_the_new_job_upon_quitting_the_current_job': {'header': 'Are you available to start work on the new job upon quitting the current job?', 'index': 104},
    'are_you_available_to_work_in_the_next_2_weeks': {'header': 'Are you available to work in the next 2 weeks?', 'index': 131},
    'are_you_deployed_to_work_in_another_organisation_that_supervises_your_work': {'header': 'Are you deployed to work in another organisation that supervises your work?', 'index': 38},
    'are_you_looking_for_a_permanent_job': {'header': 'Are you looking for a permanent job?', 'index': 103},
    'are_you_satisfied_with_your_current_job': {'header': 'Are you satisfied with your current job?', 'index': 100},
    'artificial_intelligence': {'header': 'Artificial Intelligence', 'index': 25},
    'at_any_point_in_the_last_12_months_did_you_work_on_your_own_ie_without_paid_employees_while_running_your_own_business_or_trade': {'header': 'At any point in the last 12 months, did you work on your own (i.e., without paid employees) while running your own business or trade?', 'index': 187},
    'at_any_point_in_the_last_12_months_were_you_selfemployed': {'header': 'At any point in the last 12 months, were you self-employed?', 'index': 185},
    'at_any_point_in_the_last_12_months_were_you_selfemployed_2': {'header': 'At any point in the last 12 months, were you self-employed?', 'index': 186},
    'at_present_do_you_want_to_work': {'header': 'At present, do you want to work?', 'index': 128},
    'at_what_age_did_you_start_employment': {'header': 'At what age did you start employment', 'index': 115},
    'at_what_age_retire': {'header': 'At what age retire?', 'index': 169},
    'available_for_additional_work': {'header': 'Available for additional work?', 'index': 87},
    'begin_as_a_fixedterm_contract_employee_in_your_current_job': {'header': 'Begin as a fixed-term contract employee in your current job?', 'index': 96},
    'bonus_received_from_your_jobs_during_the_last_12_months': {'header': "Bonus received from your job(s) during the last 12 months", 'index': 90},
    'care_economy': {'header': 'Care economy', 'index': 24},
    'company_type': {'header': 'Company type', 'index': 124},
    'company_type_2': {'header': 'Company type', 'index': 165},
    'contact_number': {'header': 'Contact Number', 'index': 3},
    'contract_duration': {'header': 'Contract duration', 'index': 95},
    'contract_duration_2': {'header': 'Contract duration', 'index': 111},
    'date_of_birth_ddmmyyyy': {'header': 'Date of Birth (DD/MM/YYYY)', 'index': 1},
    'did_you_experience_difficulties_while_trying_to_secure_a_job': {'header': 'Did you experience difficulties while trying to secure a job?', 'index': 138},
    'did_you_perform_any_freelance_or_assignmentbased_work_via_any_of_the_following_online_platforms_in_the_last_12_months': {'header': 'Did you perform any freelance or assignment-based work via any of the following online platform(s) in the last 12 months?', 'index': 188},
    'did_your_employer_give_you_at_least_one_rest_day_each_week': {'header': 'Did your employer give you at least one rest day each week?', 'index': 99},
    'did_your_employer_give_you_paid_leave_or_compensation_instead': {'header': 'Did your employer give you paid leave or compensation instead?', 'index': 97},
    'did_your_employer_give_you_paid_sick_leave_when_you_were_on_mc': {'header': 'Did your employer give you paid sick leave when you were on MC', 'index': 98},
    'did_your_foreign_domestic_workers_receive_any_bonus_during_the_last_12_months_including_the_13th_month_annual_wage_supplement': {'header': "Did your Foreign Domestic Worker(s) receive any bonus during the last 12 months (including the 13th month Annual Wage Supplement)?", 'index': 7},
    'digital_skills_excluding_artificial_intelligence': {'header': 'Digital skills (excluding Artificial Intelligence)', 'index': 26},
    'do_you_hire_any_foreign_domestic_workers_in_this_household': {'header': 'Do you hire any Foreign Domestic Workers in this household?', 'index': 5},
    'do_you_intend_to_look_for_a_job_in_the_future': {'header': 'Do you intend to look for a job in the future?', 'index': 182},
    'do_you_prefer_to_work_fulltime_or_parttime': {'header': 'Do you prefer to work full-time or part-time?', 'index': 184},
    'do_you_usually_set_the_price_for_the_goods_or_services_you_provide_in_this_job': {'header': 'Do you usually set the price for the goods or services you provide in this job?', 'index': 42},
    'employed_for_at_least_10_months_during_the_last_12_months': {'header': 'Employed for at least 10 months during the last 12 months?', 'index': 91},
    'employment_status': {'header': 'Employment Status', 'index': 109},
    'employment_status_2': {'header': 'Employment Status', 'index': 142},
    'employment_status_3': {'header': 'Employment Status', 'index': 177},
    'employment_status_as_of_last_week': {'header': 'Employment Status as of last week', 'index': 33},
    'ever_relocated_from_singapore_to_other_countries_for_work': {'header': 'Ever relocated from Singapore to other countries for work?', 'index': 117},
    'ever_relocated_from_singapore_to_other_countries_for_work_2': {'header': 'Ever relocated from Singapore to other countries for work?', 'index': 158},
    'field_of_study_of_your_highest_academic_qualification_attained': {'header': 'Field of study of your highest academic qualification attained?', 'index': 18},
    'full_name': {'header': 'Full Name', 'index': 0},
    'gmi': {'header': 'GMI', 'index': 89},
    'green_economy': {'header': 'Green economy', 'index': 27},
    'have_you_already_secured_a_job': {'header': 'Have you already secured a job?', 'index': 129},
    'have_you_ever_obtained_any_vocational_or_skills_certificatesqualifications_eg_wsq_and_ess_certificates_or_formal_certifications_that_validate_knowledge_and_skills_in_a_particular_field': {'header': 'Have you ever obtained any Vocational or Skills certificates/qualifications, (e.g. (WSQ) and (ESS) certificates, or formal certifications that validate knowledge and skills in a particular field)?', 'index': 20},
    'have_you_ever_retired_from_any_job': {'header': 'Have you ever retired from any job?', 'index': 30},
    'have_you_ever_retired_from_any_job_2': {'header': 'Have you ever retired from any job?', 'index': 168},
    'have_you_ever_worked_before_excluding_fulltime_national_service': {'header': 'Have you ever worked before? (excluding full-time National Service)', 'index': 141},
    'have_you_ever_worked_before_excluding_fulltime_national_service_2': {'header': 'Have you ever worked before (excluding full-time National Service)?', 'index': 175},
    'have_you_utilised_any_of_the_following_programmesinitiatives_to_upgrade_your_skills_or_switch_jobs': {'header': 'Have you utilised any of the following programmes/initiatives to upgrade your skills or switch jobs?', 'index': 29},
    'highest_academic_qualification': {'header': 'Highest Academic Qualification', 'index': 17},
    'how_did_that_work_stint_arise': {'header': 'How did that work stint arise?', 'index': 120},
    'how_did_that_work_stint_arise_2': {'header': 'How did that work stint arise?', 'index': 161},
    'how_did_you_look_for_a_job_or_employment_during_the_last_4_weeks': {'header': 'How did you look for a job or employment during the last 4 weeks?', 'index': 102},
    'how_long_have_you_been_looking_for_a_job_in_weeks': {'header': 'How long have you been looking for a job? (in weeks)', 'index': 133},
    'how_many_foreign_domestic_workers_do_you_have': {'header': 'How many Foreign Domestic Workers do you have?', 'index': 6},
    'how_many_jobs_did_you_hold_last_week': {'header': 'How many jobs did you hold last week?', 'index': 92},
    'how_much_dividends_and_interests_did_you_receive_from_other_investment_sources_eg_bonds_shares_unit_trust_personal_loans_to_persons_outside_your_households_in_the_last_12_months': {'header': 'How much dividends and interests did you receive from other investment sources (e.g., bonds, shares, unit trust, personal loans to persons outside your households) in the last 12 months?', 'index': 195},
    'how_much_interest_did_you_receive_from_savings_eg_current_and_saving_accounts_fixed_deposits_in_the_last_12_months': {'header': 'How much interest did you receive from savings (e.g., current and saving accounts, fixed deposits) in the last 12 months?', 'index': 192},
    'how_soon_do_you_expect_to_start_working_in_this_new_job': {'header': 'How soon do you expect to start working in this new job?', 'index': 130},
    'i_was_keen_in_this_job_and_took_it_up_because': {'header': 'I was keen in this job and took it up because:', 'index': 77},
    'i_was_not_keen_in_this_job_but_still_took_it_up_because': {'header': 'I was not keen in this job, but still took it up because:', 'index': 78},
    'identification_type': {'header': 'Identification Type', 'index': 10},
    'if_no_what_about_at_any_point_in_time_from_12_months_ago_till_now': {'header': 'If no, what about at any point in time from 12 months ago till now?', 'index': 127},
    'importance_of_skills_for_doing_your_job': {'header': "Importance of skill(s) for doing your job", 'index': 46},
    'importance_of_skills_for_doing_your_job_10': {'header': "Importance of skill(s) for doing your job", 'index': 69},
    'importance_of_skills_for_doing_your_job_2': {'header': "Importance of skill(s) for doing your job", 'index': 49},
    'importance_of_skills_for_doing_your_job_3': {'header': "Importance of skill(s) for doing your job", 'index': 52},
    'importance_of_skills_for_doing_your_job_4': {'header': "Importance of skill(s) for doing your job", 'index': 55},
    'importance_of_skills_for_doing_your_job_5': {'header': "Importance of skill(s) for doing your job", 'index': 58},
    'importance_of_skills_for_doing_your_job_6': {'header': "Importance of skill(s) for doing your job", 'index': 61},
    'importance_of_skills_for_doing_your_job_7': {'header': "Importance of skill(s) for doing your job", 'index': 63},
    'importance_of_skills_for_doing_your_job_8': {'header': "Importance of skill(s) for doing your job", 'index': 65},
    'importance_of_skills_for_doing_your_job_9': {'header': "Importance of skill(s) for doing your job", 'index': 67},
    'in_the_last_12_months_did_you_do_any_work_related_to_the_licences_held': {'header': 'In the last 12 months, did you do any work related to the licence(s) held?', 'index': 190},
    'in_the_last_12_months_did_you_hold_the_following_licences_or_permits': {'header': 'In the last 12 months, did you hold the following licence(s) or permits?', 'index': 189},
    'in_your_view_what_level_of_qualification_if_any_is_needed_to_carry_out_the_tasks_and_duties_of_your_jobbusiness': {'header': 'In your view, what level of qualification, if any, is needed to carry out the tasks and duties of your job/business?', 'index': 71},
    'in_your_view_which_field_of_study_is_needed_to_carry_out_the_tasks_and_duties_of_your_jobbusiness': {'header': 'In your view, which field of study is needed to carry out the tasks and duties of your job/business?', 'index': 72},
    'industry_40': {'header': 'Industry 4.0', 'index': 28},
    'is_heshe_disabledill': {'header': 'Is he/she disabled/ill?', 'index': 83},
    'is_heshe_disabledill_2': {'header': 'Is he/she disabled/ill?', 'index': 154},
    'is_heshe_disabledill_3': {'header': 'Is he/she disabled/ill?', 'index': 172},
    'is_the_main_reason_for_looking_for_a_new_job_to_better_utilise_your_skills': {'header': 'Is the main reason for looking for a new job to better utilise your skills?', 'index': 105},
    'is_this_business_incorporated_eg_name_of_business_ends_with_private_limited_or_its_equivalent': {'header': 'Is this business incorporated (e.g., name of business ends with private limited or its equivalent)?', 'index': 41},
    'is_your_salary_paid_by_an_employmentlabour_contracting_agency_eg_bgc_group_persolkelly': {'header': 'Is your salary paid by an employment/labour contracting agency (e.g., BGC Group, PERSOLKELLY)?', 'index': 37},
    'job_industry_or_sector_you_worked_in': {'header': 'Job industry or sector you worked in', 'index': 122},
    'job_industry_or_sector_you_worked_in_2': {'header': 'Job industry or sector you worked in', 'index': 163},
    'job_title': {'header': 'Job Title', 'index': 43},
    'job_title_2': {'header': 'Job Title', 'index': 112},
    'job_title_3': {'header': 'Job Title', 'index': 143},
    'job_title_4': {'header': 'Job Title', 'index': 178},
    'job_title_you_worked_in': {'header': 'Job title you worked in', 'index': 121},
    'job_title_you_worked_in_2': {'header': 'Job title you worked in', 'index': 162},
    'labour_force_status': {'header': 'Labour Force Status', 'index': 32},
    'last_drawn_gmi': {'header': 'Last drawn GMI', 'index': 123},
    'last_drawn_gmi_2': {'header': 'Last drawn GMI', 'index': 147},
    'last_drawn_gmi_3': {'header': 'Last drawn GMI', 'index': 164},
    'level_of_skills_needed_to_do_your_job': {'header': 'Level of skills needed to do your job', 'index': 47},
    'level_of_skills_needed_to_do_your_job_2': {'header': 'Level of skills needed to do your job', 'index': 50},
    'level_of_skills_needed_to_do_your_job_3': {'header': 'Level of skills needed to do your job', 'index': 53},
    'level_of_skills_needed_to_do_your_job_4': {'header': 'Level of skills needed to do your job', 'index': 56},
    'level_of_skills_needed_to_do_your_job_5': {'header': 'Level of skills needed to do your job', 'index': 59},
    'level_of_skills_you_have': {'header': "Level of skill(s) you have", 'index': 48},
    'level_of_skills_you_have_2': {'header': "Level of skill(s) you have", 'index': 51},
    'level_of_skills_you_have_3': {'header': "Level of skill(s) you have", 'index': 54},
    'level_of_skills_you_have_4': {'header': "Level of skill(s) you have", 'index': 57},
    'level_of_skills_you_have_5': {'header': "Level of skill(s) you have", 'index': 60},
    'location_of_work': {'header': 'Location of work', 'index': 125},
    'location_of_work_2': {'header': 'Location of work', 'index': 166},
    'main_reason_for_leaving_your_last_job_due_to_care': {'header': 'Main reason for leaving your last job due to care', 'index': 155},
    'main_reason_for_not_working_and_not_looking_for_job': {'header': 'Main reason for not working and not looking for job', 'index': 173},
    'main_reason_for_working_parttime_rather_than_fulltime': {'header': 'Main reason for working part-time rather than full-time:', 'index': 84},
    'main_tasks_duties': {'header': 'Main tasks / duties', 'index': 44},
    'main_tasks_duties_2': {'header': 'Main tasks / duties', 'index': 113},
    'main_tasks_duties_3': {'header': 'Main tasks / duties', 'index': 144},
    'main_tasks_duties_4': {'header': 'Main tasks / duties', 'index': 179},
    'marital_status': {'header': 'Marital Status', 'index': 15},
    'name_of_establishment_you_were_working_last_week': {'header': 'Name of Establishment you were working last week?', 'index': 73},
    'name_of_establishment_you_were_working_last_worked': {'header': 'Name of Establishment you were working last worked', 'index': 114},
    'name_of_establishment_you_were_working_last_worked_2': {'header': 'Name of Establishment you were working last worked', 'index': 145},
    'name_of_establishment_you_were_working_last_worked_3': {'header': 'Name of Establishment you were working last worked', 'index': 180},
    'number_of_children_given_birth_to': {'header': 'Number of children given birth to', 'index': 16},
    'number_of_job_changes_in_the_last_2_years': {'header': 'Number of Job changes in the last 2 years', 'index': 106},
    'place_of_birth': {'header': 'Place of Birth', 'index': 9},
    'place_of_study_for_your_highest_academic_attained_in': {'header': 'Place of study for your Highest Academic Attained in?', 'index': 19},
    'please_elaborate_on_the_main_reason_for_leaving_your_last_job': {'header': 'Please elaborate on the main reason for leaving your last job:', 'index': 149},
    'please_elaborate_on_the_main_reason_for_leaving_your_last_job_illness_injuryaccident': {'header': 'Please elaborate on the main reason for leaving your last job (illness /Injury/accident)', 'index': 151},
    'please_elaborate_on_the_main_reason_for_leaving_your_last_job_temporary_in_nature': {'header': 'Please elaborate on the main reason for leaving your last job (Temporary in nature)', 'index': 150},
    'please_indicate_the_amount_you_received_from_interest_from_savings_in_the_last_12_months_eg_current_and_saving_accounts_fixed_deposits': {'header': 'Please indicate the amount you received from interest from savings in the last 12 months (e.g., current and saving accounts, fixed deposits)?', 'index': 194},
    'please_indicate_the_main_difficulty_encountered': {'header': 'Please indicate the main difficulty encountered:', 'index': 139},
    'please_indicate_the_main_reason_you_were_holding_the_licences_but_not_doing_related_work_in_the_last_12_months': {'header': 'Please indicate the main reason you were holding the licence(s) but not doing related work in the last 12 months?', 'index': 191},
    'race': {'header': 'Race', 'index': 11},
    'reason_that_working_part_time_rather_than_full_time': {'header': 'Reason that working part time rather than full time?', 'index': 80},
    'sex': {'header': 'Sex', 'index': 8},
    'tenancy_of_household': {'header': 'Tenancy of Household', 'index': 4},
    'the_business_or_trade_you_operatedhelping_in_last_week_was_aan': {'header': 'The business or trade you operated/helping in last week was a/an:', 'index': 39},
    'the_organisation_that_employed_you_last_week_was_aan': {'header': 'The organisation that employed you last week was a/an:', 'index': 34},
    'the_person_you_are_mainly_taking_care_of_is_your': {'header': 'The person you are mainly taking care of is your', 'index': 81},
    'the_person_you_are_mainly_taking_care_of_is_your_2': {'header': 'The person you are mainly taking care of is your', 'index': 152},
    'the_person_you_are_mainly_taking_care_of_is_your_3': {'header': 'The person you are mainly taking care of is your', 'index': 170},
    'total_duration': {'header': 'Total Duration', 'index': 119},
    'total_duration_2': {'header': 'Total Duration', 'index': 160},
    'type_of_employment': {'header': 'Type of Employment?', 'index': 94},
    'type_of_employment_2': {'header': 'Type of Employment?', 'index': 110},
    'typically_savings_accounts_current_accounts_or_fixed_deposits_accrue_interest_even_for_modest_balances_for_example_an_account_with_1000_might_earn_2_to_5_per_year_in_interest_considering_this_would_you_like_to_revise_your_answer_about_interest_earned': {'header': 'Typically, savings accounts, current accounts or fixed deposits accrue interest, even for modest balances. For example, an account with $1,000 might earn $2 to $5 per year in interest. Considering this, would you like to revise your answer about interest earned?', 'index': 193},
    'usual_hours_of_work': {'header': 'Usual hours of work', 'index': 79},
    'usual_hours_of_work_2': {'header': 'Usual hours of work', 'index': 108},
    'usual_hours_of_work_3': {'header': 'Usual hours of work', 'index': 146},
    'usual_hours_of_work_4': {'header': 'Usual hours of work', 'index': 181},
    'was_your_main_job_last_week_a_paid_internship_traineeship_or_apprenticeship': {'header': 'Was your main job last week a paid internship, traineeship or apprenticeship?', 'index': 35},
    'were_you_actively_looking_for_jobs_in_the_past_4_weeks': {'header': 'Were you actively looking for jobs in the past 4 weeks?', 'index': 126},
    'what_age_retire': {'header': 'What age retire?', 'index': 31},
    'what_is_hisher_age': {'header': 'What is his/her age?', 'index': 82},
    'what_is_hisher_age_2': {'header': 'What is his/her age?', 'index': 153},
    'what_is_hisher_age_3': {'header': 'What is his/her age?', 'index': 171},
    'what_is_the_field_of_study_of_your_highest_vocational_or_skills_certificatequalification': {'header': 'What is the field of study of your highest vocational or skills certificate/qualification?', 'index': 22},
    'what_is_the_highest_vocational_or_skills_certificatequalification_obtained': {'header': 'What is the highest vocational or skills certificate/qualification obtained?', 'index': 21},
    'what_is_your_main_reason_for_living_abroad': {'header': 'What is your main reason for living abroad?', 'index': 13},
    'what_is_your_main_reason_for_not_working_and_not_looking_for_a_job': {'header': 'What is your main reason for not working and not looking for a job?', 'index': 167},
    'what_is_your_religion': {'header': 'What is your religion?', 'index': 14},
    'what_kind_of_occupation_were_you_looking_for': {'header': 'What kind of occupation were you looking for?', 'index': 135},
    'what_other_difficulties_did_you_encounter_while_trying_to_secure_a_job': {'header': 'What other difficulties did you encounter while trying to secure a job?', 'index': 140},
    'what_other_steps_have_you_taken_to_look_for_employment_in_the_last_4_weeks': {'header': 'What other steps have you taken to look for employment in the last 4 weeks?', 'index': 137},
    'what_was_the_main_reason_you_left_your_last_job': {'header': 'What was the main reason you left your last job?', 'index': 148},
    'what_was_the_main_reason_you_were_in_a_paid_internship_traineeship_or_apprenticeship': {'header': 'What was the main reason you were in a paid internship, traineeship, or apprenticeship?', 'index': 36},
    'what_was_the_main_step_you_took_to_look_for_employment_in_the_last_4_weeks': {'header': 'What was the main step you took to look for employment in the last 4 weeks?', 'index': 136},
    'what_were_your_reasons_for_being_selfemployed': {'header': 'What were your reason(s) for being self-employed?', 'index': 74},
    'what_were_your_reasons_for_taking_up_this_job': {'header': 'What were your reason(s) for taking up this job?', 'index': 76},
    'when_did_you_begin_working_for_your_current_employer': {'header': 'When did you begin working for your current employer?', 'index': 93},
    'when_did_you_leave_your_last_job': {'header': 'When did you leave your last job?', 'index': 107},
    'when_did_you_leave_your_last_job_in_months': {'header': 'When did you leave your last job? (In months)', 'index': 157},
    'when_did_you_leave_your_last_job_months': {'header': 'When did you leave your last job? (Months)', 'index': 176},
    'when_do_you_intend_to_look_for_a_job': {'header': 'When do you intend to look for a job?', 'index': 183},
    'when_was_your_first_such_experience': {'header': 'When was your first such experience?', 'index': 118},
    'when_was_your_first_such_experience_2': {'header': 'When was your first such experience?', 'index': 159},
    'when_will_you_be_available_to_work': {'header': 'When will you be available to work?', 'index': 132},
    'where_are_you_currently_staying': {'header': 'Where are you currently staying?', 'index': 12},
    'where_is_the_place_of_study_for_your_highest_vocational_or_skills_certificatequalification': {'header': 'Where is the place of study for your highest vocational or skills certificate/qualification?', 'index': 23},
    'which_of_the_following_statements_best_describe_your_skills_in_relation_to_what_is_needed_for_your_jobbusiness': {'header': 'Which of the following statements best describe your skills in relation to what is needed for your job/business?', 'index': 45},
    'while_currently_looking_for_work_waiting_to_start_work_are_you': {'header': 'While currently looking for work / waiting to start work, are you:', 'index': 134},
    'willing_to_work_additional_hours': {'header': 'Willing to work additional hours?', 'index': 86},
    'would_you_prefer_to_be_aan': {'header': 'Would you prefer to be a/an', 'index': 75},
    'would_you_work_fulltime_if_suitable_care_services_were_available_andor_affordable': {'header': 'Would you work full-time if suitable care services were available and/or affordable?', 'index': 85},
    'would_you_work_fulltime_if_suitable_care_services_were_available_andor_affordable_2': {'header': 'Would you work full-time if suitable care services were available and/or affordable?', 'index': 156},
    'would_you_work_if_suitable_care_services_were_made_available_andor_affordable': {'header': 'Would you work if suitable care services were made available and/or affordable?', 'index': 174},
}

__all__ = ['HEADERS_MAPPING']
